# Configuration #
# Compilator
CC		= gcc

# Executables to build 
EXEC		= bow2bow0

# Sources files

# Include directories
INCLUDEDIRS 	= ../../include ../../include/kmlocal ../../include/densetrack

# Compilation and link flags
CFLAGS 		= $(patsubst %,-I%,$(subst :, ,$(INCLUDEDIRS)))
LDFLAGS 	= -lsvm -lkmeans -ldensetrack

.PHONY: clean cleanall

all: $(EXEC)
$(EXEC): main.o naomngt.o naokmeans.o naosvm.o 
	$(CC) -Wall -o $@  $^ -L../../lib $(LDFLAGS)
main.o: main.cpp 
	$(CC) -Wall -o $@ -c $< $(CFLAGS)
naomngt.o: naomngt.cpp 
	$(CC) -Wall -o $@ -c $< $(CFLAGS)
naokmeans.o: naokmeans.cpp
	$(CC) -Wall -o $@ -c $< $(CFLAGS)
naosvm.o: naosvm.cpp
	$(CC) -Wall -o $@ -c $< $(CFLAGS)
clean:
	rm -f *~
cleanall: clean
	rm -f *.o $(EXEC)
